### ISSUE TITLE
managedClusters resource not available in selected region

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-cli#409]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

In the CLI we should only show the regions where the resources are available

C:\Users\brcaspar\source\pcs-cli>pcs --versionOverride actions-bug-bash --dockerTagOverride testing -s standard -r java
? Enter a solution name: brcaspar-actions-bugbash
? Select a subscription: IOTS
? Select a location: South Central US
? Enter prefix for .azurewebsites.net: brcaspar-actions-bugbash
✓ Application registered: https://portal.azure.com/iotsl.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/objectId/fe340bb4-77da-4b50-997e-9957bebf460e/appId/7629aaca-1248-4dba-b913-4a13871d0ed2
✓ Created resource group: https://portal.azure.com/iotsl.onmicrosoft.com#resource/subscriptions/d7ca9718-3a3c-4ce8-8ec9-76a6396c0206/resourceGroups/brcaspar-actions-bugbash
✕ Deployment validation failed:
{
  "code": "LocationNotAvailableForResourceType",
  "message": "The provided location 'southcentralus' is not available for resource type 'Microsoft.ContainerService/managedClusters'. List of available regions for the resource type is 'eastus,westeurope,centralus,canadacentral,canadaeast,uksouth,westus,westus2,australiaeast,northeurope,japaneast,eastus2,southeastasia,ukwest'."
}
Error: {"code":"LocationNotAvailableForResourceType","message":"The provided location 'southcentralus' is not available for resource type 'Microsoft.ContainerService/managedClusters'. List of available regions for the resource type is 'eastus,westeurope,centralus,canadacentral,canadaeast,uksouth,westus,westus2,australiaeast,northeurope,japaneast,eastus2,southeastasia,ukwest'."}
...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
Register the provider.

Below is the instruction:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors#solution-3---azure-portal

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Node.js Runtime: ...

**Comment by sakimsft** [comment]
It is because the provider (Microsoft.ContainerService) was not registered automatically for some subscriptions.
A customer who sees this error needs to register the provider manually. 
(See Known workarounds for instruction)

IcM ticket has created and assigned to ACS to see if the provider can be registered automatically to all subscriptions.

**Comment by avneet723** [comment]
@sakimsft could you please update the TSG with the appropriate set of guidelines for the customers?

**Comment by sakimsft** [comment]
@avneet723 
I already added TSG under PCS at below location since I could not find Wiki or TSG for CLI.
https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Troubleshooting-Guide#Resolve-errors-for-resource-provider-registration

If you have other preferable location to document, please let me know - I will add document accordingly.
